Repository Ahmedelsa3eed/Student-Unity, pull requests merged in 2022-12, with the labels that each got.

#44 Implementing some requests regarding registered courses retrieval and manipulation
  Student-Unity-frontend/src/app/components/my-courses/my-courses.component.html
  Student-Unity-frontend/src/app/components/my-courses/my-courses.component.ts
  Student-Unity-frontend/src/app/models/Course.ts
  Student-Unity-frontend/src/app/services/courses.service.ts
  Student-Unity/src/main/java/csed/swe/studentunity/API/AllCoursesAPI.java
  Student-Unity/src/main/java/csed/swe/studentunity/DAO/CourseRepo.java
  Student-Unity/src/main/java/csed/swe/studentunity/DAO/RegisteredCourseRepository.java
  Student-Unity/src/main/java/csed/swe/studentunity/Logic/AdminCheckInterceptor.java
  Student-Unity/src/main/java/csed/swe/studentunity/Logic/AllCourseService.java
  Student-Unity/src/main/java/csed/swe/studentunity/config/InterceptorConfig.java
  Student-Unity/src/main/java/csed/swe/studentunity/model/Course.java
  Student-Unity/src/main/java/csed/swe/studentunity/model/RegisteredCourse.java
  Student-Unity/src/main/java/csed/swe/studentunity/model/RegisteredCourseId.java
  Student-Unity/src/main/java/csed/swe/studentunity/model/Task.java
Labels: Backend

#40 feat: create tasks component
  Student-Unity-frontend/src/app/app-routing.module.ts
  Student-Unity-frontend/src/app/app.module.ts
  Student-Unity-frontend/src/app/components/account-page/account-page.component.ts
  Student-Unity-frontend/src/app/components/home/home.component.css
  Student-Unity-frontend/src/app/components/navigation-bar/navigation-bar.component.html
  Student-Unity-frontend/src/app/components/navigation-bar/navigation-bar.component.ts
  Student-Unity-frontend/src/app/components/shared/match.validator.ts
  Student-Unity-frontend/src/app/components/task/task.component.css
  Student-Unity-frontend/src/app/components/task/task.component.html
  Student-Unity-frontend/src/app/components/task/task.component.spec.ts
  Student-Unity-frontend/src/app/components/task/task.component.ts
  Student-Unity-frontend/src/app/components/tasks-page/tasks-page.component.css
  Student-Unity-frontend/src/app/components/tasks-page/tasks-page.component.html
  Student-Unity-frontend/src/app/components/tasks-page/tasks-page.component.spec.ts
  Student-Unity-frontend/src/app/components/tasks-page/tasks-page.component.ts
  Student-Unity-frontend/src/app/models/Status.ts
  Student-Unity-frontend/src/app/models/Task.ts
  Student-Unity-frontend/src/app/services/student-task.service.spec.ts
  Student-Unity-frontend/src/app/services/student-task.service.ts
  Student-Unity-frontend/src/environments/environment.ts
  Student-Unity-frontend/src/styles.css
  Student-Unity/src/main/java/csed/swe/studentunity/API/AccountAPI.java
  Student-Unity/src/main/java/csed/swe/studentunity/API/LoginAPI.java
  Student-Unity/src/main/java/csed/swe/studentunity/API/StudentTaskAPI.java
  Student-Unity/src/main/java/csed/swe/studentunity/API/TaskAPI.java
  Student-Unity/src/main/java/csed/swe/studentunity/Logic/Accounts/AccountInterceptor.java
  Student-Unity/src/main/java/csed/swe/studentunity/Logic/Accounts/AccountService.java
  Student-Unity/src/main/java/csed/swe/studentunity/Logic/LoginService.java
  Student-Unity/src/main/java/csed/swe/studentunity/Logic/Tasks/StudentTaskService.java
  Student-Unity/src/main/java/csed/swe/studentunity/Logic/Tasks/TaskService.java
  Student-Unity/src/main/java/csed/swe/studentunity/config/InterceptorConfig.java
  Student-Unity/src/main/java/csed/swe/studentunity/model/LoginResponses.java
  Student-Unity/src/main/java/csed/swe/studentunity/model/User.java
  Student-Unity/src/test/java/csed/swe/studentunity/Logic/StudentTaskServiceTest.java
  Student-Unity/src/test/java/csed/swe/studentunity/account/AccountServiceTest.java
Labels: Frontend

#46 Fix/java test coaverage
  .github/workflows/backend.yml
  Student-Unity/pom.xml
  Student-Unity/sonar-project.properties
  Student-Unity/src/main/java/csed/swe/studentunity/Logic/AdminCheckInterceptor.java
  Student-Unity/src/main/java/csed/swe/studentunity/config/InterceptorConfig.java
Labels: bug

#84 feat: using AWS RDS
  Student-Unity/src/main/resources/application.properties
Labels: AWS
